
name: Build and Deploy biolord 0.0.3 to GHCR
on:
  push:
    branches:
      - prod
    paths:
      - "tools/biolord/v0.0.3/**"

env:
  REGISTRY: ghcr.io
  ORG: scleestacks
  REPOSITORY: biolord
  VER: 0.0.3
  BUILD_PATH: tools/biolord/v0.0.3

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-7`" >> $GITHUB_ENV

      - name: Build, tag, and push docker image to GHCR
        run: |
          docker build -t $REGISTRY/$ORG/$REPOSITORY:$VER $BUILD_PATH
          docker push $REGISTRY/$ORG/$REPOSITORY:$VER
